# Generated by Django 6.0.7 on 2026-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USUARIO', 'Usuario'), ('RRHH', 'RRHH'), ('CONTABILIDAD', 'Contabilidad')], default='USUARIO', max_length=20),
        ),
    ]
