# Generated by Django 6.0.7 on 2026-07-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
    ]
