# Generated by Django 6.0.7 on 2026-07-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="validationrule",
            options={
                "verbose_name": "Regla de Validación",
                "verbose_name_plural": "Reglas de Validación",
            },
        ),
        migrations.AlterModelOptions(
            name="validationtask",
            options={
                "verbose_name": "Tarea de Validación",
                "verbose_name_plural": "Tareas de Validación",
            },
        ),
    ]
