# Generated by Django 6.0.7 on 2026-07-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
            },
        ),
    ]
